#!/usr/bin/env sh

echo "Running pre-commit checks..."

npm run type-check
if [ $? -ne 0 ]; then
  echo "Type check failed. Commit aborted."
  exit 1
fi

npx lint-staged
if [ $? -ne 0 ]; then
  echo "Lint failed. Commit aborted."
  exit 1
fi

npm run test:ci
if [ $? -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "All checks passed!"
